[package]
name = "ncda-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
ncda-common = { path = "../ncda-common" }
aya-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "ncda"
path = "src/main.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(bpf_target_arch, values("x86_64", "aarch64"))'] }
